"""
Django settings for restroomsaround project.

Generated by 'django-admin startproject' using Django 1.8.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
import sys
from os.path import join

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

PROJECT_PATH = os.path.dirname(os.path.abspath(__file__))


sys.path.append(PROJECT_PATH)
sys.path.append(join(PROJECT_PATH, 'apps'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'e-*11(qj%ko1zs-i9+5p(x%7!ll^v^tq$zn^kqrt!_-9k@4o$='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

DEFAULT_APPS = (
	'django.contrib.admin',
	'django.contrib.auth',
	'django.contrib.contenttypes',
	'django.contrib.sessions',
	'django.contrib.messages',
	'django.contrib.staticfiles',
	'django.contrib.gis',
)

OUR_APPS = (
	'apps.location',
	)

INSTALLED_APPS = DEFAULT_APPS + OUR_APPS

MIDDLEWARE_CLASSES = (
	'django.contrib.sessions.middleware.SessionMiddleware',
	'django.middleware.common.CommonMiddleware',
	'django.middleware.csrf.CsrfViewMiddleware',
	'django.contrib.auth.middleware.AuthenticationMiddleware',
	'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
	'django.contrib.messages.middleware.MessageMiddleware',
	'django.middleware.clickjacking.XFrameOptionsMiddleware',
	'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'restroomsaround.urls'

TEMPLATES = [
	{
		'BACKEND': 'django.template.backends.django.DjangoTemplates',
		'DIRS': [join(PROJECT_PATH, 'templates')],
		'APP_DIRS': True,
		'OPTIONS': {
			'context_processors': [
				'django.template.context_processors.debug',
				'django.template.context_processors.request',
				'django.contrib.auth.context_processors.auth',
				'django.contrib.messages.context_processors.messages',
			],
		},
	},
]

WSGI_APPLICATION = 'restroomsaround.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

#openshift
if 'OPENSHIFT_POSTGRESQL_DB_URL' in os.environ:
	DATABASES = {
	'default': {
		'ENGINE': 'django.contrib.gis.db.backends.postgis',
		'NAME': os.environ['OPENSHIFT_APP_NAME'],
		'USER': 'admin',
		'PASSWORD': "admin",
		'HOST': os.environ['OPENSHIFT_POSTGRESQL_DB_HOST'],
		'PORT': os.environ['OPENSHIFT_POSTGRESQL_DB_PORT'],
		}
	}
else:
	DATABASES = {
		'default': {
			'ENGINE': 'django.contrib.gis.db.backends.postgis',
			'NAME': 'restroomdb',
			'USER':'taranjeetsingh',
			'PASSWORD':'gameover',
		}
	}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'
if 'OPENSHIFT_REPO_DIR' in os.environ:
    STATIC_ROOT = os.path.join(os.environ.get('OPENSHIFT_REPO_DIR'), 'wsgi', 'static')
else:
	STATIC_ROOT = os.path.join(BASE_DIR, 'static')

STATICFILES_DIRS = (
	os.path.join(PROJECT_PATH, 'static'),
)

STATICFILES_FINDERS = (
	'django.contrib.staticfiles.finders.AppDirectoriesFinder',
	'django.contrib.staticfiles.finders.FileSystemFinder',
)
